export const FETCH_BOOK_USERS = "bookUsersPage/FETCH_BOOK_USERS"

export const FETCH_BOOK_USERS_PENDING = "bookUsersPage/FETCH_BOOK_USERS_PENDING"
export const FETCH_BOOK_USERS_FULFILLED = "bookUsersPage/FETCH_BOOK_USERS_FULFILLED"
export const FETCH_BOOK_USERS_REJECTED = "bookUsersPage/FETCH_BOOK_USERS_REJECTED"