export const FETCH_TOP_THREE_SHOWS = "header/FETCH_TOP_THREE_SHOWS"

export const FETCH_TOP_THREE_SHOWS_PENDING = "header/FETCH_TOP_THREE_SHOWS_PENDING"
export const FETCH_TOP_THREE_SHOWS_FULFILLED = "header/FETCH_TOP_THREE_SHOWS_FULFILLED"
export const FETCH_TOP_THREE_SHOWS_REJECTED = "header/FETCH_TOP_THREE_SHOWS_REJECTED"