export const FETCH_SINGLE_SHOW = 'commentsPage/FETCH_SINGLE_SHOW'

export const FETCH_SINGLE_SHOW_PENDING = 'commentsPage/FETCH_SINGLE_SHOW_PENDING'
export const FETCH_SINGLE_SHOW_FULFILLED = 'commentsPage/FETCH_SINGLE_SHOW_FULFILLED'
export const FETCH_SINGLE_SHOW_REJECTED = 'commentsPage/FETCH_SINGLE_SHOW_REJECTED'