export const FETCH_BOOK_POSTS = 'bookFeedPage/FETCH_BOOK_POSTS'

export const FETCH_BOOK_POSTS_PENDING = "bookFeedPage/FETCH_BOOK_POSTS_PENDING"
export const FETCH_BOOK_POSTS_FULFILLED = "bookFeedPage/FETCH_BOOK_POSTS_FULFILLED"
export const FETCH_BOOK_POSTS_REJECTED = "bookFeedPage/FETCH_BOOK_POSTS_REJECTED"

export const DISPLAY_TEXT_MODAL = "bookFeedPage/DISPLAY_TEXT_MODAL"
export const HIDE_TEXT_MODAL = "bookFeedPage/HIDE_TEXT_MODAL"

export const DISPLAY_IMAGE_MODAL = "bookFeedPage/DISPLAY_IMAGE_MODAL"
export const HIDE_IMAGE_MODAL = "bookFeedPage/HIDE_IMAGE_MODAL"

export const DISPLAY_VIDEO_MODAL = "bookFeedPage/DISPLAY_VIDEO_MODAL"
export const HIDE_VIDEO_MODAL = "bookFeedPage/HIDE_VIDEO_MODAL"

export const DISPLAY_ALL_POSTS = "bookFeedPage/DISPLAY_ALL_POSTS"
export const DISPLAY_TEXT_POSTS = "bookFeedPage/DISPLAY_TEXT_POSTS"
export const DISPLAY_IMAGE_POSTS = "bookFeedPage/DISPLAY_IMAGE_POSTS"
export const DISPLAY_VIDEO_POSTS = "bookFeedPage/DISPLAY_VIDEO_POSTS"
