export const FETCH_BOOK_POSTS = 'bookFeedPage/FETCH_BOOK_POSTS'

export const FETCH_BOOK_POSTS_PENDING = "bookFeedPage/FETCH_BOOK_POSTS_PENDING"
export const FETCH_BOOK_POSTS_FULFILLED = "bookFeedPage/FETCH_BOOK_POSTS_FULFILLED"
export const FETCH_BOOK_POSTS_REJECTED = "bookFeedPage/FETCH_BOOK_POSTS_REJECTED"

export const DISPLAY_TEXT_MODAL = "bookFeedPage/DISPLAY_TEXT_MODAL"
export const HIDE_TEXT_MODAL = "bookFeedPage/HIDE_TEXT_MODAL"
