export const FETCH_FALSE_USERS = 'falseUsersPage/FETCH_FALSE_USERS'

export const FETCH_FALSE_USERS_PENDING = 'falseUsersPage/FETCH_FALSE_USERS_PENDING'
export const FETCH_FALSE_USERS_FULFILLED = 'falseUsersPage/FETCH_FALSE_USERS_FULFILLED'
export const FETCH_FALSE_USERS_REJECTED = 'falseUsersPage/FETCH_FALSE_USERS_REJECTED'