export const DISPLAY_LOGIN = "loginPage/DISPLAY_LOGIN"
export const DISPLAY_REGISTER = "loginPage/DISPLAY_REGISTER"

export const REGISTER_USER = "loginPage/REGISTER_USER"
export const REGISTER_USER_PENDING = 'loginPage/REGISTER_USER_PENDING'
export const REGISTER_USER_FULFILLED = 'loginPage/REGISTER_USER_FULFILLED'
export const REGISTER_USER_REJECTED = 'loginPage/REGISTER_USER_REJECTED'
