export const FETCH_AUTHORS_POSTS = "authorsPosts/FETCH_AUTHORS_POSTS"

export const FETCH_AUTHORS_POSTS_PENDING = "authorsPosts/FETCH_AUTHORS_POSTS_PENDING"
export const FETCH_AUTHORS_POSTS_FULFILLED = "authorsPosts/FETCH_AUTHORS_POSTS_FULFILLED"
export const FETCH_AUTHORS_POSTS_REJECTED = "authorsPosts/FETCH_AUTHORS_POSTS_REJECTED"

export const FETCH_AUTHOR = "authorsPosts/FETCH_AUTHOR"

export const FETCH_AUTHOR_PENDING = "authorsPosts/FETCH_AUTHOR_PENDING"
export const FETCH_AUTHOR_FULFILLED = "authorsPosts/FETCH_AUTHOR_FULFILLED"
export const FETCH_AUTHOR_REJECTED = "authorsPosts/FETCH_AUTHOR_REJECTED"