export const FETCH_BLOG_POSTS = 'blogPage/FETCH_BLOG_POSTS'

export const FETCH_BLOG_POSTS_PENDING = 'blogPage/FETCH_BLOG_POSTS_PENDING'
export const FETCH_BLOG_POSTS_FULFILLED = 'blogPage/FETCH_BLOG_POSTS_FULFILLED'
export const FETCH_BLOG_POSTS_REJECTED = 'blogPage/FETCH_BLOG_POSTS_REJECTED'