export const SEARCH_SHOWS = "searchInput/SEARCH_SHOWS"

export const SEARCH_SHOWS_PENDING = "searchInput/SEARCH_SHOWS_PENDING"
export const SEARCH_SHOWS_FULFILLED = "searchInput/SEARCH_SHOWS_FULFILLED"
export const SEARCH_SHOWS_REJECTED = "searchInput/SEARCH_SHOWS_REJECTED"