export const FETCH_BOOK_TEXT_POST = 'bookPostDetail/FETCH_BOOK_TEXT_POST'
export const FETCH_BOOK_TEXT_POST_PENDING = 'bookPostDetail/FETCH_BOOK_TEXT_POST_PENDING'
export const FETCH_BOOK_TEXT_POST_FULFILLED = 'bookPostDetail/FETCH_BOOK_TEXT_POST_FULFILLED'
export const FETCH_BOOK_TEXT_POST_REJECTED = 'bookPostDetail/FETCH_BOOK_TEXT_POST_REJECTED'

export const FETCH_BOOK_IMAGE_POST = 'bookPostDetail/FETCH_BOOK_IMAGE_POST'
export const FETCH_BOOK_IMAGE_POST_PENDING = 'bookPostDetail/FETCH_BOOK_IMAGE_POST_PENDING'
export const FETCH_BOOK_IMAGE_POST_FULFILLED = 'bookPostDetail/FETCH_BOOK_IMAGE_POST_FULFILLED'
export const FETCH_BOOK_IMAGE_POST_REJECTED = 'bookPostDetail/FETCH_BOOK_IMAGE_POST_REJECTED'

export const FETCH_BOOK_VIDEO_POST = 'bookPostDetail/FETCH_BOOK_VIDEO_POST'
export const FETCH_BOOK_VIDEO_POST_PENDING = 'bookPostDetail/FETCH_BOOK_VIDEO_POST_PENDING'
export const FETCH_BOOK_VIDEO_POST_FULFILLED = 'bookPostDetail/FETCH_BOOK_VIDEO_POST_FULFILLED'
export const FETCH_BOOK_VIDEO_POST_REJECTED = 'bookPostDetail/FETCH_BOOK_VIDEO_POST_REJECTED'

export const FETCH_CURRENT_USER = 'bookPostDetail/FETCH_CURRENT_USER'
export const FETCH_CURRENT_USER_PENDING = 'bookPostDetail/FETCH_CURRENT_USER_PENDING'
export const FETCH_CURRENT_USER_FULFILLED = 'bookPostDetail/FETCH_CURRENT_USER_FULFILLED'
export const FETCH_CURRENT_USER_REJECTED = 'bookPostDetail/FETCH_CURRENT_USER_REJECTED'

export const DELETE_POST = 'bookPostDetail/DELETE_POST'
export const DELETE_POST_PENDING = 'bookPostDetail/DELETE_POST_PENDING'
export const DELETE_POST_FULFILLED = 'bookPostDetail/DELETE_POST_FULFILLED'
export const DELETE_POST_REJECTED = 'bookPostDetail/DELETE_POST_REJECTED'
