export const FETCH_SHOW_DETAILS_AND_CAST = "showDetailsPage/FETCH_SHOW_DETAILS_AND_CAST"

export const FETCH_SHOW_DETAILS_AND_CAST_PENDING = "showDetailsPage/FETCH_SHOW_DETAILS_AND_CAST_PENDING"
export const FETCH_SHOW_DETAILS_AND_CAST_FULFILLED = "showDetailsPage/FETCH_SHOW_DETAILS_AND_CAST_FULFILLED"
export const FETCH_SHOW_DETAILS_AND_CAST_REJECTED = "showDetailsPage/FETCH_SHOW_DETAILS_AND_CAST_REJECTED"

export const FETCH_SHOWS_CREW = "showDetailsPage/FETCH_SHOWS_CREW"

export const FETCH_SHOWS_CREW_PENDING = 'showDetailsPage/FETCH_SHOWS_CREW_PENDING'
export const FETCH_SHOWS_CREW_FULFILLED = 'showDetailsPage/FETCH_SHOWS_CREW_FULFILLED'
export const FETCH_SHOWS_CREW_REJECTED = 'showDetailsPage/FETCH_SHOWS_CREW_REJECTED'

export const FETCH_SHOWS_EPISODES = "showDetailsPage/FETCH_SHOWS_EPISODES"

export const FETCH_SHOWS_EPISODES_PENDING = 'showDetailsPage/FETCH_SHOWS_EPISODES_PENDING'
export const FETCH_SHOWS_EPISODES_FULFILLED = 'showDetailsPage/FETCH_SHOWS_EPISODES_FULFILLED'
export const FETCH_SHOWS_EPISODES_REJECTED = 'showDetailsPage/FETCH_SHOWS_EPISODES_REJECTED'

export const CLEAR_EPISODES_AND_CREW = 'showDetailsPage/CLEAR_EPISODES_AND_CREW'

